[build]
  # Build command for your epic UniGO landing page
  command = "npm run build"
  
  # Directory to publish (Vite's default output)
  publish = "dist"
  
  # Node.js version for optimal performance (Vite requires 20.19+ or 22.12+)
  [build.environment]
    NODE_VERSION = "22.14.0"
    NPM_VERSION = "10"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  # Handle client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for optimal performance and security
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

# Specific headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Headers for the APK file
[[headers]]
  for = "/UniGO.apk"
  [headers.values]
    Content-Type = "application/vnd.android.package-archive"
    Cache-Control = "public, max-age=86400"

# Form handling (if needed for future features)
[build.processing]
  skip_processing = false

# Edge functions (for future enhancements)
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Plugin configuration for optimal performance
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

# Branch deploy settings
[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"
